Add support for znode flag
tommyulfsparre/aurora_exporter pull request #19
Opened 2017-02-22 20:26 UTC by zircote

This allows for the aurora scheduler znode to be passed as
a flag at runtime. We rely on zk for multiple clusters and to enable this to work for us
it become necessary to allow us to direct the scraper to the correct znode. Let me know
your feedback on the pr looking forward to hearing back.

2017-02-23 19:30 UTC, tommyulfsparre requested changes

2017-02-23 19:30 UTC, tommyulfsparre commented on finder.go
> +func newFinder(url string, znode string) (f finder, err error) {
nit: you only need to specify the type once: `url, znode string`

2017-02-23 19:30 UTC, tommyulfsparre commented on finder.go
> +func newZkFinder(url string, znode string) *zkFinder {
same

2017-02-23 19:30 UTC, tommyulfsparre commented on main.go
> +	zkPath     = flag.String("zk.path", "/aurora/scheduler", "zkNode that aurora matains master election.")
s/matains/maintains/g

2017-02-23 19:30 UTC, tommyulfsparre commented on finder.go
>  const (
nit: remove the parentheses

2017-02-23 19:36 UTC, tommyulfsparre commented
@zircote thanks! just a few nits. 

Also, as of Aurora `0.16.0` [curator](http://curator.apache.org/) will be the default ZooKeeper client and this will no longer work for detecting the scheduler.

2017-02-23 22:20 UTC, zircote commented
@tommyulfsparre do you have any preferences regarding how best to resolve this? Do you want to support `<0.16.0` or just update it to support `>=0.16.0`?

2017-02-24 08:15 UTC, tommyulfsparre approved these changes

2017-02-24 08:18 UTC, tommyulfsparre commented
@zircote so I think of not adding curator support for now and later support both, toggled with a cmdline flag.

2017-02-24 08:18 UTC, merged