Fix: empty help strings
tommyulfsparre/aurora_exporter pull request #25
Opened 2018-10-09 18:26 UTC by DeviaVir

This fixes:
``` 
# curl localhost:9104/metrics
An error has occurred during metrics collection:

62 error(s) occurred:
* empty help string
* empty help string
* empty help string
* empty help string
* [...times 62...]
```
and no metrics being returned at all.

I know some of these don't make sense, but at least it made the aurora exporter work again for me.

2018-10-26 08:41 UTC, DeviaVir commented
@tommyulfsparre ping?

2018-10-26 23:25 UTC, tommyulfsparre requested changes

2018-10-26 23:25 UTC, tommyulfsparre commented on vars.go
> +		"Number of 200OK response events.",
```suggestion
		"Number of HTTP 200 status response events.",
```

2018-10-26 23:25 UTC, tommyulfsparre commented on vars.go
> +		"Timed 200OK response total.",
```suggestion
		"Timed HTTP 200 status response total.",
```

2018-10-26 23:25 UTC, tommyulfsparre commented on vars.go
> +		"Number of 200OK response events per second.",
```suggestion
		"Number of HTTP 200 status response events per second.",
```

2018-10-26 23:25 UTC, tommyulfsparre commented on vars.go
> +		"Timed 200OK responses per event.",
```suggestion
		"Timed HTTP 200 status responses per event.",
```

2018-10-26 23:25 UTC, tommyulfsparre commented on vars.go
> +		"Number of 200OK response events total per second.",
```suggestion
		"Number of HTTP 200 status response events total per second.",
```

2018-10-26 23:25 UTC, tommyulfsparre commented on vars.go
> +		"Number of queue size.",
```suggestion
		"Current pubsub executor queue size.",
```

2018-10-26 23:25 UTC, tommyulfsparre commented on vars.go
> +		"NUmber of penalty MS per event.",
```suggestion
		"Number of scheduled task penalty in millisecond per event.",
```

2018-10-26 23:25 UTC, tommyulfsparre commented on vars.go
> +		"Number of penalty MS total per second.",
```suggestion
		"Number of scheduled task penalty in millisecond total per event.",
```

2018-10-26 23:25 UTC, tommyulfsparre commented on vars.go
> +		"TImed penalty events total.",
```suggestion
		"Timed penalty events total.",
```

2018-10-26 23:29 UTC, tommyulfsparre commented
@DeviaVir Thanks! 
I couldn't reproduce this myself with `prometheus/client_golang` version 0.8.0 and 0.9.0. Which version did you build against?

2018-10-27 15:27 UTC, DeviaVir commented
@tommyulfsparre 
> I couldn't reproduce this myself with prometheus/client_golang version 0.8.0 and 0.9.0. Which version did you build against?

here's a dockerfile to reproduce against:
```
FROM library/golang:latest # 1.11.1 at this time
RUN go get github.com/tommyulfsparre/aurora_exporter \
  && go build github.com/tommyulfsparre/aurora_exporter
```
then using that aurora_exporter and trying to curl `/metrics` ended up in the error in OP

2018-10-27 15:31 UTC, DeviaVir commented
@tommyulfsparre updated the PR to include your requested changes.

2018-10-28 09:01 UTC, tommyulfsparre approved these changes

2018-10-28 09:02 UTC, merged

2018-10-28 09:02 UTC, tommyulfsparre commented
@DeviaVir thanks!